// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TASK03.Context;

#nullable disable

namespace TASK03.Migrations
{
    [DbContext(typeof(ContextClass))]
    partial class ContextClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TASK03.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeptName = "HR"
                        },
                        new
                        {
                            Id = 2,
                            DeptName = "PR"
                        },
                        new
                        {
                            Id = 3,
                            DeptName = "Social Media"
                        },
                        new
                        {
                            Id = 4,
                            DeptName = "Finance"
                        });
                });

            modelBuilder.Entity("TASK03.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "cairoA",
                            Age = 22,
                            DepartmentId = 1,
                            Name = "Ramy"
                        },
                        new
                        {
                            Id = 2,
                            Address = "CairoB",
                            Age = 32,
                            DepartmentId = 2,
                            Name = "Mai"
                        },
                        new
                        {
                            Id = 3,
                            Address = "CairoC",
                            Age = 42,
                            DepartmentId = 3,
                            Name = "Ali"
                        },
                        new
                        {
                            Id = 4,
                            Address = "CairoD",
                            Age = 52,
                            DepartmentId = 4,
                            Name = "Omar"
                        },
                        new
                        {
                            Id = 5,
                            Address = "CairoE",
                            Age = 2,
                            DepartmentId = 1,
                            Name = "Mostafa"
                        },
                        new
                        {
                            Id = 6,
                            Address = "CairoF",
                            Age = 38,
                            DepartmentId = 2,
                            Name = "Ahmed"
                        },
                        new
                        {
                            Id = 7,
                            Address = "CairoG",
                            Age = 48,
                            DepartmentId = 3,
                            Name = "Sara"
                        },
                        new
                        {
                            Id = 8,
                            Address = "CairoH",
                            Age = 26,
                            DepartmentId = 4,
                            Name = "Osama"
                        },
                        new
                        {
                            Id = 9,
                            Address = "CairoI",
                            Age = 3,
                            DepartmentId = 1,
                            Name = "Mohamed"
                        },
                        new
                        {
                            Id = 10,
                            Address = "CairoJ",
                            Age = 46,
                            DepartmentId = 2,
                            Name = "Nour"
                        },
                        new
                        {
                            Id = 11,
                            Address = "CairoK",
                            Age = 22,
                            DepartmentId = 3,
                            Name = "Mohamed"
                        },
                        new
                        {
                            Id = 12,
                            Address = "CairoL",
                            Age = 46,
                            DepartmentId = 4,
                            Name = "Nour"
                        });
                });

            modelBuilder.Entity("TASK03.Models.Student", b =>
                {
                    b.HasOne("TASK03.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TASK03.Models.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
